ALTER TABLE orders
ADD COLUMN status VARCHAR(10) NOT NULL CHECK (
    status IN ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED')
) DEFAULT 'NEW',
ADD COLUMN accrual NUMERIC NOT NULL CHECK (accrual >= 0) DEFAULT 0,
ADD COLUMN uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
